routes/web.php
<?php

use App\Model\Stockcode;
use App\Model\Category;
use App\Model\Product;
use App\Model\Brand;
use App\Model\Location;
use App\Model\Uom;
use App\Model\Debtor;
use App\Model\Creditor;
use App\Model\Cylinder;
use App\Model\Cylindercategory;
use App\Model\Cylindergroup;
use App\Model\Cylinderproduct;
use App\Model\Cylindertype;
use App\Model\Cylindervalvetype;
use App\Model\Cylinderhandwheeltype;
use App\Model\Manufacturer;
use App\Model\DeliveryNote;
use App\Model\PurchasedTable;
use App\Model\Gasrack;
use App\Model\PrintedIndexView;
use App\Model\Cashbill;
use App\Model\Invoice;
use App\Model\SystemSetup;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

// Route::get('/',function() {
//    return view("app");
// });



Route::get('/', function () {
    return redirect('home');
});



Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('clear/test', function () {
        Artisan::call('cache:clear');
        Artisan::call('route:clear');
        Artisan::call('config:clear');
        Artisan::call('view:clear');
        dd("success");
});

    Route::post('cashbills/auth/minprice', 'CashbillController@getAuthenticateAjax')->name('auth.minprice.post');

    Route::resource('stockmaster/stockcodes', 'StockcodeController');

    Route::resource('stockmaster/products', 'ProductController');

    Route::resource('stockmaster/category', 'CategoryController');

    Route::resource('stockmaster/brands', 'BrandController');

    Route::resource('stockmaster/locations', 'LocationController');

    Route::resource('stockmaster/uom', 'UOMController');

    Route::resource('stockmaster/adjustmentits', 'AdjustmentitController');

    Route::resource('stockmaster/adjustmentots', 'AdjustmentotController');

    Route::resource('stockmaster/reasons', 'ReasonController');

    Route::resource('stockmaster/areas', 'AreaController');

    Route::resource('stockmaster/currencies', 'CurrencyController');

    Route::resource('stockmaster/customertypes', 'CustomerController');

    Route::resource('stockmaster/salesman', 'SalesmanController');

    Route::resource('stockmaster/equipments', 'EquipmentController');

    Route::resource('stockmaster/equipments', 'EquipmentController');

    Route::resource('cylindermaster/gasracks', 'GasrackController');
    Route::get('reportprinting/gasracksactivity/print', 'GasrackActivityController@print')->name('gasracksactivity.print');
    Route::get('cylindermaster/gasracks/gasrackcylinder/{id}', 'GasrackController@storeCylinder')->name('gasracks.storeCylinder');
    Route::get('cylindermaster/gasracks/search/filter', 'Gasrackcontroller@filter_records')->name('gasracks.search.filter');
    Route::get('cylindermaster/gasracks/search/rnfilter/{accountcode}', 'Gasrackcontroller@rn_filter_records')->name('gasracks.search.rnfilter');
    Route::delete('cylindermaster/gasracks/destroycylinders/{cylinder}', 'Gasrackcontroller@destroycylinder')->name('gasracks.destroycylinder');
    Route::delete('cylindermaster/gasracks/destroyslings/{sling}', 'Gasrackcontroller@destroysling')->name('gasracks.destroysling');

    Route::resource('cylindermaster/slings', 'SlingController');

    Route::resource('cylindermaster/shackles', 'ShackleController');


    Route::get('cylindermaster/cylinders/cylinderactivity', 'CylinderController@cylinderactivity')->name('cylinders.cylinderactivity');

    Route::get('cylindermaster/cylinders/cylinderactivity/listing', 'CylinderController@cylinderActivityListing')->name('cylinders.cylinderactivity.listing');

    Route::resource('cylindermaster/cylinders', 'CylinderController');
    Route::get('reportprinting/cylindermaster/print', 'CylinderController@print')->name('cylinders.print');
    Route::get('reportprinting/cylindermovement/print', 'CylinderMovementController@print')->name('cylindersmovement.print');
    Route::get('reportprinting/cylinderledger/print', 'CylinderLedgerController@print')->name('cylinderledger.print');
    Route::get('reportprinting/cylinderRental/print', 'CylinderRentalController@print')->name('cylinderRental.print');
    Route::get('reportprinting/Location/print', 'CylinderLocationController@print')->name('cylinderlocation.print');
    Route::get('reportprinting/CylinderSummaryHolding/print', 'CylinderSummaryHoldingController@print')->name('CylinderSummaryHolding.print');
    Route::get('reportprinting/CylinderActivity/print', 'CylinderActivityController@print')->name('CylinderActivity.print');
    Route::get('reportprinting/CylinderInvalid/print', 'CylinderInvalidController@print')->name('CylinderInvalid.print');
    Route::get('cylindermaster/search/filter', 'CylinderController@filter_records')->name('cylinders.search.filter');
    Route::get('cylindermaster/search/rnfilter/{accountcode}', 'CylinderController@rn_filter_records')->name('cylinders.search.rnfilter');
    Route::get('cylindermaster/search/cylinderfilter', 'CylinderController@getCylinderDetail')->name('cylinders.search.cylinderfilter');

    Route::get('cylindermaster/search/checkfilter', 'CylinderController@check_cylinders')->name('cylinders.check.filter');

    Route::get('cylindermaster/gasracks/search/checkfilter', 'Gasrackcontroller@check_slings')->name('slings.check.filter');

    Route::get('cylindermaster/slings/search/filter', 'SlingController@filter_records')->name('slings.search.filter');

    Route::resource('cylindermaster/cylindercategory', 'CylindercategoryController');


    Route::resource('cylindermaster/cylindergroups', 'CylindergroupController');


    Route::resource('cylindermaster/cylinderproducts', 'CylinderproductController');


    Route::delete('dailypro/goods/edit/{id}', 'GoodController@destroyGooddt')->name('goods.destroyGooddt');

    Route::get('reportprinting/debtormasterlisting/print', 'DebtorController@print')->name('debtors.print');

    Route::get('reportprinting/creditormasterlisting/print', 'CreditorController@print')->name('creditors.print');

    Route::get('reportprinting/stockmasterlisting/print', 'StockcodeController@print')->name('stock.print');

    Route::get('reportprinting/stockbalance/print', 'StockreportController@printStkBal')->name('stockbal.print');

    Route::get('reportprinting/stockledger/print', 'StockLedgerController@printStkLedger')->name('stockled.print');

    Route::get('reportprinting/stockmovement/print', 'StockMovementController@printStkMovement')->name('stockmov.print');

    Route::get('reportprinting/stockvaluefifo/print', 'StockValueController@printFIFO')->name('stockvalfifo.print');

    Route::get('reportprinting/stockvalueasat/print', 'StockValueController@printASAT')->name('stockvalasat.print');

    Route::resource('stockmaster/debtors', 'DebtorController');

    Route::resource('stockmaster/creditors', 'CreditorController');

    Route::get('stockmaster/creditors/api/get', 'CreditorController@api_get')->name('creditors.api.get');

    Route::get('stockmaster/debtors/api/get', 'DebtorController@api_get')->name('debtors.api.get');

    Route::resource('cylindermaster/cylindertypes', 'CylindertypeController');

    Route::resource('cylindermaster/cylindercontainertypes', 'CylindercontainertypeController');

    Route::resource('cylindermaster/cylinderhandwheeltypes', 'CylinderhandwheeltypeController');

    Route::resource('cylindermaster/cylindervalvetypes', 'CylindervalvetypeController');

    Route::resource('cylindermaster/gasracktypes', 'GasracktypeController');

    Route::resource('cylindermaster/slingtypes', 'SlingtypeController');

    Route::resource('cylindermaster/shackletypes', 'ShackletypeController');

    Route::resource('cylindermaster/manufacturers', 'ManufacturerController');

    Route::resource('cylindermaster/ownerships', 'OwnershipController');

    Route::resource('dailypro/preturns', 'PreturnController');
    Route::get('dailypro/preturns/report/print', 'PreturnController@print')->name('preturns.print');
    Route::get('dailypro/preturns/report/jasper/{id}/purchasedreturn', 'PreturnController@jasper')->name('preturns.jasper');

    Route::delete('dailypro/preturns/edit/{id}', 'PreturnController@destroyPreturndt')->name('preturns.destroyPreturndt');

    Route::resource('dailypro/cashbills', 'CashbillController');

    Route::get('dailypro/cashbills/report/print', 'CashbillController@print')->name('cashbills.print');

    Route::get('dailypro/cashbills/report/jasper/data/cashbills', 'CashbillController@jasper')->name('cashbills.jasper');

    Route::delete('dailypro/cashbills/edit/{id}', 'CashbillController@destroyCashbilldt')->name('cashbills.destroyCashbilldt');

    // Route::resource('dailypro/invoices', 'InvoiceController');
    Route::resource('settings/documentsetups', 'DocumentSetupController');

    Route::resource('settings/dnrnsetups', 'DNRNSetupController');

    Route::resource('dailypro/quotations', 'QuotationController');
    Route::get('dailypro/quotations/report/print', 'QuotationController@print')->name('quotations.print');
    Route::get('dailypro/quotations/report/jasper/{id}/quotation', 'QuotationController@jasper')->name('quotations.jasper');

    Route::delete('dailypro/quotations/edit/{id}', 'QuotationController@destroyQuotationdt')->name('quotations.destroyQuotationdt');

    Route::resource('dailypro/deliveryorders', 'DeliveryorderController');
    Route::get('dailypro/deliveryorders/report/print', 'DeliveryorderController@print')->name('deliveryorders.print');
    Route::get('dailypro/deliveryorders/report/jasper/{id}/deliveryorder', 'DeliveryorderController@jasper')->name('deliveryorders.jasper');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Model\Stockcode;

class Product extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'code',
        'descr',
        'active',
        'created_by',
        'updated_by',
        'deleted_by'
    ];
    
    public function user()
    {
        return $this->belongsTo('App\User', 'userid');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Model\Product;
use Illuminate\Http\Request;
use PHPJasper\PHPJasper;
use Auth;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //$products = product::latest()->paginate(10);
        $data["products"] = Product::get();
        // $data["products"] = Product::orderBy('created_at', 'asc')->latest()->paginate(10);
        // $data["pagetitle"] = "Add Product";
        // $data["products"] = product::latest()->paginate(10);
        $data["page_title"] = "Product Item Listing";
        $data["bclvl1"] = "Product Item Listing";
        $data["bclvl1_url"] = route('products.index');
        //return view("products.index", compact('products'))->with('i', (request()->input('page', 1) - 1) * 10);
        //return response()->json($data);
        // dd('test');
        return view('stockmaster.products.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data["page_title"] = "Add Product";
        $data["bclvl1"] = "Product Item Listing";
        $data["bclvl1_url"] = route('products.index');
        $data["bclvl2"] = "Add Product";
        $data["bclvl2_url"] = route('products.create');

        return view('stockmaster.products.create',$data);
    }

    public function store(Request $request)
    {
        $product = Product::create([
            'code' => $request['code'],
            'descr' => $request['descr'],
            'active' => $request['active'],
            'created_by'=> Auth::user()->id
        ]);

        return redirect()->route('products.index')->with('Success', 'Product created successfully.');
    }

    public function show(product $product)
    {
        $product = Product::where('id', $product->id)->first();
        $data = [];
        $data['product'] = $product;

        return view('stockmaster.products.show', compact('product'));
    }

    public function edit($id)
    {
        $data["product"] = Product::find($id);
        $data["bclvl1"] = "Product Item Listing";
        $data["bclvl1_url"] = route('products.index');
        $data["page_title"] = "Edit Product";
        $data["bclvl2"] = "Edit Product";
        $data["bclvl2_url"] = route('products.edit', ['id'=>$id]);
        return view('stockmaster.products.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        // return response()->json($request);
        if (isset($product)) {
            $product->update([
                'code' => $request['code'],
                'descr' => $request['descr'],
                'active' => $request['active'],
                'updated_by'=> Auth::user()->id
            ]);
        }
        return redirect()->route('products.index')->with('Success', 'Product updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(product $product)
    {
        $product->update([
            'deleted_by' => Auth::user()->id
        ]);
        $product->delete();
        return redirect()->route('products.index')->with('Success', 'Product deleted successfully.');
    }

    public function print()
    {
        $Products = Product::all();

        $dataArray = array();
        $no = 1;
        foreach ($Products as $Product) {
            $objectJSON = [];
            $objectJSON["no"] = $no;
            $objectJSON["code"] = $Product->code;
            $objectJSON["description"] = $Product->descr;
            $objectJSON["status"] = $Product->active ? "Active":"Inactive";

            $no = $no + 1;
            $dataArray[] = collect($objectJSON);
        }

        $ProductsJSON = '{"data" :' . json_encode($dataArray) . '}';

        $JsonFileName = "ReportPrintProduct" . date("Ymdhisa");

        file_put_contents(base_path('resources/reporting/StockModule/' . $JsonFileName . '.json'), $ProductsJSON);
        $JasperFileName = "ReportPrintProduct" . date("Ymdhisa");;
        $file = $this->printReport($JsonFileName, $JasperFileName);

        header('Content-Description: application/pdf');
        header('Content-Type: application/pdf');
        header('Content-Disposition:; filename=' . $JasperFileName . 'pdf');
        readfile($file);
        unlink($file);
        flush();
    }

    public function printReport($JsonFileName, $JasperFileName)
    {
        $input = base_path() . '/resources/reporting/StockModule/ReportPrint.jrxml';
        $output = base_path() . '/resources/reporting/StockModule/' . $JasperFileName;

        $data_file = base_path() . '/resources/reporting/StockModule/' . $JsonFileName . '.json';

        $options = [
            'format' => ['pdf'],
            'params' => [
                "company_name" => config('config.company.name'),
                "company_no" => config('config.company.company_no'),
                "title" => "Product Listing Report (" .  date('d/m/Y') .")"
            ],
            'locale' => 'en',
            'db_connection' => [
                'driver' => 'json',
                'data_file' => $data_file,
                'json_query' => 'data'
            ]
        ];

        $jasper = new PHPJasper;

        $jasper->process(
            $input,
            $output,
            $options
        )->execute();
        unlink($data_file);
        $file = base_path() . '/resources/reporting/StockModule/' . $JasperFileName . '.pdf';
        return $file;
    }
    public function download()
    {
        return "hi";
    }
}

resources/views/stockmaster/products/create.blade.php
@extends('master')
@section('content')


<div class="box box-solid">
    <div class="box-header"></div>

    <div class="box-body with-border">
        <form action ="{{ route('products.store') }}" method="POST">
            @csrf
            @include('stockmaster/products/form')

        </form>
    </div>
</div>


@endsection

resources/views/stockmaster/products/edit.blade.php
@extends('master')
@section('content')

<div class="box box-solid">
    <div class="box-header"></div>

    <div class="box-body with-border">
        <form action ="{{ route('products.update', $product->id) }}" method="POST">
            <input type="hidden" name="_method" value="PUT"/>
            @csrf
            @include('stockmaster/products/form')

        </form>
    </div>
</div>


@endsection

resources/views/stockmaster/products/form.blade.php
<div class="form-group row">
    <label for="code" class="col-md-2"> Code <span class="text-danger">*</span></label>
    <div class="col-md-10">
        <input name="code" type="text" maxlength="50" class="form-control" value="{{ isset($product)?$product->code:'' }}" required>
    </div>
</div>

<div class="form-group row">
    <label for="description" class="col-md-2">Description <span class="text-danger">*</span></label>
    <div class="col-md-10">
        <input name="descr" type="text" maxlength="100" class="form-control" value="{{ isset($product)?$product->descr:'' }}" required>
    </div>
</div>

<div class="form-group row">		
    <label class="control-label col-md-2">Active</label>
    <div class="col-md-10">
        <div class="radio-list">
            <label class="radio-inline">
            <input type="radio" name="active" value="1" {{ isset($product)?($product->active=='1')? 'checked' : '': 'checked' }}/> Active </font></label>
            <label class="radio-inline">
            <input type="radio" name="active" value="0" {{ isset($product)?($product->active=='0')? 'checked' : '': '' }}/> Non-Active </font></label>
        </div>
    </div>
</div>

<div class="form-group">
    <button type="submit" class="btn btn-primary">Submit</button>
</div>

resources/views/stockmaster/products/index.blade.php
@extends('master')

@section('content')

@if(Auth::user()->hasPermissionTo('IV_MD_PRODUCT_CR'))
    <div class="row">
        <div class="col-4">
            <div class="col-lg-12 text-left" style="margin-top:10px;margin-bottom: 10px;">
                <a class="btn btn-success " href="{{ route('products.create') }}"> Add Product</a>
            </div>
        </div>
        {{-- <div class="col-4">
        </div>
        <div class="col-2" style="left: 50px;">
            <div class="col-lg-12 text-left" style="margin-top:10px;margin-bottom: 10px;">
                <a class="btn btn-primary" target="_blank" style="width: 100%;" href="{{ route('product.print') }}"> Print (pdf)</a>
            </div>
        </div>
        <div class="col-2">
            <div class="col-lg-12 text-left" style="margin-top:10px;margin-bottom: 10px;">
                <a class="btn btn-primary" target="_blank" style="width: 100%;" href="{{ route('product.download') }}"> Download
                    (csv)</a>
            </div>
        </div> --}}
    </div>
@endif

{{-- @if ($message = Session::get('success'))
        <div class="alert alert-success">
            {{ $message }}
</div>
@endif --}}


@if (Session::has('Success'))
<div class="alert white-alert text-secondary" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p>{{ Session::get('Success') }}</p>
</div>
@endif
@php ($i = 0)

<div class="card">
    <div class="card-body">
        <div class="bg-white">
            <div class="table-responsive">
                <table id="productTab" class="table table-bordered table-striped" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Code</th>
                            <th>Description</th>
                            <th width="280px">Action</th>
                        </tr>
                    </thead>
                    @if(sizeof($products) > 0)
                    <tbody>
                        @foreach ($products as $product)
                        <tr>

                            <td>{{ ++$i }}</td>
                            @if(Auth::user()->hasPermissionTo('IV_MD_PRODUCT_UP'))
                                <td><a href="{{ route('products.edit',$product->id) }}">{{ $product->code }}</a></td>
                            @else
                            <td>
                                {{ $product->code }}
                            </td>
                            @endif
                            {{-- <td>{{ $product->code}}</td> --}}
                            <td>{{ $product->descr }}</td>
                            @if(Auth::user()->hasPermissionTo('IV_MD_PRODUCT_DL'))
                                <td>
                                    @if(!$product->isUsedInStockcode())
                                    <a href="{{ route('products.destroy', $product->id) }}" data-method="delete"
                                        data-confirm="Confirm delete this account?">
                                        <i class="fa fa-trash"></i></a>
                                    @endif
                                </td>
                            @else
                                <td></td>
                            @endif
                        </tr>
                        @endforeach
                    </tbody>
                    @endif
                </table>
            </div>
        </div>
    </div>
</div>


{{-- {!! $products->links() !!} --}}

@endsection

@push('scripts')
<script>
$(document).ready(function() {

            $('#productTab').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'excelHtml5',
                    'csvHtml5',
                    'pdfHtml5'
                ]
            });
        } );
</script>

<script src="https://cdn.datatables.net/buttons/1.6.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.html5.min.js"></script>
@endpush

resources/views/stockmaster/products/show.blade.php
@extends('master')
@section('content')

<div class="col-md-12">
    <div class="box box-solid box-default">
        <div class="box-header with-border">Product</div>

        <div class="box-body with-border">
            <div class="form-group row">
                <label for="code" class="col-md-2"> Code : </label>
                <label for="code" class="col-md-10"> {{  $product->code }}</label>
                
            </div>
            
            <div class="form-group row">
                <label for="description" class="col-md-2">Description : </label>
                <label for="description" class="col-md-10"> {{  $product->descr }}</label>
            </div>
            
            <div class="form-group row">
                <label for="descr" class="col-md-2">Active : </label>
                <label for="descr" class="col-md-10">{{  $product->active }}</label>
            </div>
        </div>
    </div>
</div>


@endsection