routes/web.php
<?php

use App\Model\Stockcode;
use App\Model\Category;
use App\Model\Product;
use App\Model\Brand;
use App\Model\Location;
use App\Model\Uom;
use App\Model\Debtor;
use App\Model\Creditor;
use App\Model\Cylinder;
use App\Model\Cylindercategory;
use App\Model\Cylindergroup;
use App\Model\Cylinderproduct;
use App\Model\Cylindertype;
use App\Model\Cylindervalvetype;
use App\Model\Cylinderhandwheeltype;
use App\Model\Manufacturer;
use App\Model\DeliveryNote;
use App\Model\PurchasedTable;
use App\Model\Gasrack;
use App\Model\PrintedIndexView;
use App\Model\Cashbill;
use App\Model\Invoice;
use App\Model\SystemSetup;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

// Route::get('/',function() {
//    return view("app");
// });



Route::get('/', function () {
    return redirect('home');
});



Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('clear/test', function () {
        Artisan::call('cache:clear');
        Artisan::call('route:clear');
        Artisan::call('config:clear');
        Artisan::call('view:clear');
        dd("success");
});

    Route::post('cashbills/auth/minprice', 'CashbillController@getAuthenticateAjax')->name('auth.minprice.post');

    Route::resource('stockmaster/stockcodes', 'StockcodeController');

    Route::resource('stockmaster/products', 'ProductController');

    Route::resource('stockmaster/category', 'CategoryController');

    Route::resource('stockmaster/brands', 'BrandController');

    Route::resource('stockmaster/locations', 'LocationController');

    Route::resource('stockmaster/uom', 'UOMController');

    Route::resource('stockmaster/adjustmentits', 'AdjustmentitController');

    Route::resource('stockmaster/adjustmentots', 'AdjustmentotController');

    Route::resource('stockmaster/reasons', 'ReasonController');

    Route::resource('stockmaster/areas', 'AreaController');

    Route::resource('stockmaster/currencies', 'CurrencyController');

    Route::resource('stockmaster/customertypes', 'CustomerController');

    Route::resource('stockmaster/salesman', 'SalesmanController');

    Route::resource('stockmaster/equipments', 'EquipmentController');

    Route::resource('stockmaster/equipments', 'EquipmentController');

    Route::resource('cylindermaster/gasracks', 'GasrackController');
    Route::get('reportprinting/gasracksactivity/print', 'GasrackActivityController@print')->name('gasracksactivity.print');
    Route::get('cylindermaster/gasracks/gasrackcylinder/{id}', 'GasrackController@storeCylinder')->name('gasracks.storeCylinder');
    Route::get('cylindermaster/gasracks/search/filter', 'Gasrackcontroller@filter_records')->name('gasracks.search.filter');
    Route::get('cylindermaster/gasracks/search/rnfilter/{accountcode}', 'Gasrackcontroller@rn_filter_records')->name('gasracks.search.rnfilter');
    Route::delete('cylindermaster/gasracks/destroycylinders/{cylinder}', 'Gasrackcontroller@destroycylinder')->name('gasracks.destroycylinder');
    Route::delete('cylindermaster/gasracks/destroyslings/{sling}', 'Gasrackcontroller@destroysling')->name('gasracks.destroysling');

    Route::resource('cylindermaster/slings', 'SlingController');

    Route::resource('cylindermaster/shackles', 'ShackleController');


    Route::get('cylindermaster/cylinders/cylinderactivity', 'CylinderController@cylinderactivity')->name('cylinders.cylinderactivity');

    Route::get('cylindermaster/cylinders/cylinderactivity/listing', 'CylinderController@cylinderActivityListing')->name('cylinders.cylinderactivity.listing');

    Route::resource('cylindermaster/cylinders', 'CylinderController');
    Route::get('reportprinting/cylindermaster/print', 'CylinderController@print')->name('cylinders.print');
    Route::get('reportprinting/cylindermovement/print', 'CylinderMovementController@print')->name('cylindersmovement.print');
    Route::get('reportprinting/cylinderledger/print', 'CylinderLedgerController@print')->name('cylinderledger.print');
    Route::get('reportprinting/cylinderRental/print', 'CylinderRentalController@print')->name('cylinderRental.print');
    Route::get('reportprinting/Location/print', 'CylinderLocationController@print')->name('cylinderlocation.print');
    Route::get('reportprinting/CylinderSummaryHolding/print', 'CylinderSummaryHoldingController@print')->name('CylinderSummaryHolding.print');
    Route::get('reportprinting/CylinderActivity/print', 'CylinderActivityController@print')->name('CylinderActivity.print');
    Route::get('reportprinting/CylinderInvalid/print', 'CylinderInvalidController@print')->name('CylinderInvalid.print');
    Route::get('cylindermaster/search/filter', 'CylinderController@filter_records')->name('cylinders.search.filter');
    Route::get('cylindermaster/search/rnfilter/{accountcode}', 'CylinderController@rn_filter_records')->name('cylinders.search.rnfilter');
    Route::get('cylindermaster/search/cylinderfilter', 'CylinderController@getCylinderDetail')->name('cylinders.search.cylinderfilter');

    Route::get('cylindermaster/search/checkfilter', 'CylinderController@check_cylinders')->name('cylinders.check.filter');

    Route::get('cylindermaster/gasracks/search/checkfilter', 'Gasrackcontroller@check_slings')->name('slings.check.filter');

    Route::get('cylindermaster/slings/search/filter', 'SlingController@filter_records')->name('slings.search.filter');

    Route::resource('cylindermaster/cylindercategory', 'CylindercategoryController');


    Route::resource('cylindermaster/cylindergroups', 'CylindergroupController');


    Route::resource('cylindermaster/cylinderproducts', 'CylinderproductController');


    Route::delete('dailypro/goods/edit/{id}', 'GoodController@destroyGooddt')->name('goods.destroyGooddt');

    Route::get('reportprinting/debtormasterlisting/print', 'DebtorController@print')->name('debtors.print');

    Route::get('reportprinting/creditormasterlisting/print', 'CreditorController@print')->name('creditors.print');

    Route::get('reportprinting/stockmasterlisting/print', 'StockcodeController@print')->name('stock.print');

    Route::get('reportprinting/stockbalance/print', 'StockreportController@printStkBal')->name('stockbal.print');

    Route::get('reportprinting/stockledger/print', 'StockLedgerController@printStkLedger')->name('stockled.print');

    Route::get('reportprinting/stockmovement/print', 'StockMovementController@printStkMovement')->name('stockmov.print');

    Route::get('reportprinting/stockvaluefifo/print', 'StockValueController@printFIFO')->name('stockvalfifo.print');

    Route::get('reportprinting/stockvalueasat/print', 'StockValueController@printASAT')->name('stockvalasat.print');

    Route::resource('stockmaster/debtors', 'DebtorController');

    Route::resource('stockmaster/creditors', 'CreditorController');

    Route::get('stockmaster/creditors/api/get', 'CreditorController@api_get')->name('creditors.api.get');

    Route::get('stockmaster/debtors/api/get', 'DebtorController@api_get')->name('debtors.api.get');

    Route::resource('cylindermaster/cylindertypes', 'CylindertypeController');

    Route::resource('cylindermaster/cylindercontainertypes', 'CylindercontainertypeController');

    Route::resource('cylindermaster/cylinderhandwheeltypes', 'CylinderhandwheeltypeController');

    Route::resource('cylindermaster/cylindervalvetypes', 'CylindervalvetypeController');

    Route::resource('cylindermaster/gasracktypes', 'GasracktypeController');

    Route::resource('cylindermaster/slingtypes', 'SlingtypeController');

    Route::resource('cylindermaster/shackletypes', 'ShackletypeController');

    Route::resource('cylindermaster/manufacturers', 'ManufacturerController');

    Route::resource('cylindermaster/ownerships', 'OwnershipController');

    Route::resource('dailypro/preturns', 'PreturnController');
    Route::get('dailypro/preturns/report/print', 'PreturnController@print')->name('preturns.print');
    Route::get('dailypro/preturns/report/jasper/{id}/purchasedreturn', 'PreturnController@jasper')->name('preturns.jasper');

    Route::delete('dailypro/preturns/edit/{id}', 'PreturnController@destroyPreturndt')->name('preturns.destroyPreturndt');

    Route::resource('dailypro/cashbills', 'CashbillController');

    Route::get('dailypro/cashbills/report/print', 'CashbillController@print')->name('cashbills.print');

    Route::get('dailypro/cashbills/report/jasper/data/cashbills', 'CashbillController@jasper')->name('cashbills.jasper');

    Route::delete('dailypro/cashbills/edit/{id}', 'CashbillController@destroyCashbilldt')->name('cashbills.destroyCashbilldt');

    // Route::resource('dailypro/invoices', 'InvoiceController');
    Route::resource('settings/documentsetups', 'DocumentSetupController');

    Route::resource('settings/dnrnsetups', 'DNRNSetupController');

    Route::resource('dailypro/quotations', 'QuotationController');
    Route::get('dailypro/quotations/report/print', 'QuotationController@print')->name('quotations.print');
    Route::get('dailypro/quotations/report/jasper/{id}/quotation', 'QuotationController@jasper')->name('quotations.jasper');

    Route::delete('dailypro/quotations/edit/{id}', 'QuotationController@destroyQuotationdt')->name('quotations.destroyQuotationdt');

    Route::resource('dailypro/deliveryorders', 'DeliveryorderController');
    Route::get('dailypro/deliveryorders/report/print', 'DeliveryorderController@print')->name('deliveryorders.print');
    Route::get('dailypro/deliveryorders/report/jasper/{id}/deliveryorder', 'DeliveryorderController@jasper')->name('deliveryorders.jasper');

app/Http/Controllers/CylindergroupController.php
<?php

namespace App\Http\Controllers;

use App\Model\Cylindergroup;
use Illuminate\Http\Request;
use Auth;

class CylindergroupController extends Controller
{
    public function index(){

        $data["cylindergroups"] = Cylindergroup::get();
        $data["page_title"] = "Group Item Listings";
        $data["bclvl1"] = "Group Item Listings";
        $data["bclvl1_url"] = route('cylindergroups.index');

        return view('cylindermaster.cylindergroups.index', $data);
    }

    public function create(){
        
        $data["page_title"] = "Add Group";
        $data["bclvl1"] = "Group Item Listings";
        $data["bclvl1_url"] = route('cylindergroups.index');
        $data["bclvl2"] = "Add Group";
        $data["bclvl2_url"] = route('cylindergroups.create');

        return view('cylindermaster.cylindergroups.create', $data);
    }

    public function store(Request $request)
    {
        $cylindergroup = Cylindergroup::create([
            'code' => $request['code'],
            'descr' => $request['descr'],
            'active' => $request['active'],
            'created_by'=> Auth::user()->id
        ]);
        return redirect()->route('cylindergroups.index')->with('Success', 'Cylindergroup created successfully.');

    }

    public function edit($id){

        $data["cylindergroup"] = Cylindergroup::find($id);
        $data["page_title"] = "Edit Group";
        $data["bclvl1"] = "Group Item Listings";
        $data["bclvl1_url"] = route('cylindergroups.index');
        $data["bclvl2"] = "Edit Group";
        $data["bclvl2_url"] = route('cylindergroups.edit', ['id'=>$id]);

        return view('cylindermaster.cylindergroups.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $cylindergroup = Cylindergroup::find($id);
        if (isset($cylindergroup)) {
            $cylindergroup->update([
                'code' => $request['code'],
                'descr' => $request['descr'],
                'active' => $request['active'],
                'updated_by'=> Auth::user()->id
            ]);
        }
        return redirect()->route('cylindergroups.index')->with('Success', 'Cylindergroup updated successfully.');
    }

    public function destroy(cylindergroup $cylindergroup)
    {
        $cylindergroup->update([
            'deleted_by' => Auth::user()->id
        ]);
        $cylindergroup->delete();
        return redirect()->route('cylindergroups.index')->with('Success', 'Cylindergroup deleted successfully.');
    }
}

resources/views/cylindermaster/cylindergroups/create.blade.php
@extends('master')
@section('content')

<div class="box box-solid">
    <div class="box-header"></div>

    <div class="box-body with-border">
        <form action ="{{ route('cylindergroups.store') }}" method="POST">
            @csrf
            @include('cylindermaster/cylindergroups/form')

        </form>
    </div>
</div>


@endsection

resources/views/cylindermaster/cylindergroups/edit.blade.php
@extends('master')
@section('content')


<div class="box box-solid">
    <div class="box-header"></div>

    <div class="box-body with-border">
        <form action ="{{ route('cylindergroups.update', $cylindergroup->id )}}" method="POST">
        <input type="hidden" name="_method" value="PUT"/>
            @csrf
            @include('cylindermaster/cylindergroups/form')

        </form>
    </div>
</div>


@endsection

resources/views/cylindermaster/cylindergroups/form.blade.php
<div class="form-group row">
        <label for="code" class="col-md-2"> Code <span class="text-danger">*</span></label>
        <div class="col-md-10">
            <input name="code" type="text" maxlength="50" class="form-control" value="{{ isset($cylindergroup)?$cylindergroup->code:'' }}" required>
        </div>
    </div>
    
    <div class="form-group row">
        <label for="description" class="col-md-2">Description <span class="text-danger">*</span></label>
        <div class="col-md-10">
            <input name="descr" type="text" maxlength="100" class="form-control" value="{{ isset($cylindergroup)?$cylindergroup->descr:'' }}" required>
        </div>
    </div>
    
    <div class="form-group row">		
        <label class="control-label col-md-2">Active</label>
        <div class="col-md-10">
            <div class="radio-list">
                <label class="radio-inline">
                <input type="radio" name="active" value="1" {{ isset($cylindergroup)?($cylindergroup->active=='1')? 'checked' : '': 'checked' }}/> Active </font></label>
                <label class="radio-inline">
                <input type="radio" name="active" value="0" {{ isset($cylindergroup)?($cylindergroup->active=='0')? 'checked' : '': '' }}/> Non-Active </font></label>
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

resources/views/cylindermaster/cylindergroups/index.blade.php
@extends('master')

@section('content')

    <div class="row">
        <div class="col-lg-12 text-left" style="margin-top:10px;margin-bottom: 10px;">
            <a class="btn btn-success " href="{{ route('cylindergroups.create') }}"> Add Group</a>
        </div>
    </div>

    {{-- @if ($message = Session::get('success'))
        <div class="alert alert-success">
            {{ $message }}
        </div>
    @endif --}}

    
    @if (Session::has('Success'))
    <div class="alert white-alert text-secondary" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <p>{{ Session::get('Success') }}</p>
    </div>

    @endif
@php ($i = 0)
    
    
<div class="card">
    <div class="card-body">
        <div class="bg-white">        
            <div class="table-responsive">
                <table id="grpTab" class="table table-bordered table-striped" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Code</th>
                            <th>Description</th>
                            <th width="280px">More</th>
                        </tr>
                    </thead>
                @if(sizeof($cylindergroups) > 0)    
                    <tbody>
                        @foreach ($cylindergroups as $cylindergroup)
                        <tr>
                        
                            <td>{{ ++$i }}</td>
                            <td><a href="{{ route('cylindergroups.edit',$cylindergroup->id) }}">{{ $cylindergroup->code }}</a></td>
                            {{-- <td>{{ $cylindergroup->code}}</td> --}}
                            <td>{{ $cylindergroup->descr }}</td>
                            <td>
                                <a href="{{ route('cylindergroups.destroy', $cylindergroup->id) }}" data-method="delete" data-confirm="Confirm delete this account?">
                                <i class="fa fa-trash"></i></a>  
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                @endif
                </table>
            </div>
        </div>
    </div>
</div>


    {{-- {!! $cylindergroups->links() !!} --}}

@endsection

@push('scripts')
<script>
$(document).ready(function() {

            $('#grpTab').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'excelHtml5',
                    'csvHtml5',
                    'pdfHtml5'
                ]
            });
        } );
</script>

<script src="https://cdn.datatables.net/buttons/1.6.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.html5.min.js"></script>
@endpush