routes/web.php
<?php

use App\Model\Stockcode;
use App\Model\Category;
use App\Model\Product;
use App\Model\Brand;
use App\Model\Location;
use App\Model\Uom;
use App\Model\Debtor;
use App\Model\Creditor;
use App\Model\Cylinder;
use App\Model\Cylindercategory;
use App\Model\Cylindergroup;
use App\Model\Cylinderproduct;
use App\Model\Cylindertype;
use App\Model\Cylindervalvetype;
use App\Model\Cylinderhandwheeltype;
use App\Model\Manufacturer;
use App\Model\DeliveryNote;
use App\Model\PurchasedTable;
use App\Model\Gasrack;
use App\Model\PrintedIndexView;
use App\Model\Cashbill;
use App\Model\Invoice;
use App\Model\SystemSetup;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

// Route::get('/',function() {
//    return view("app");
// });



Route::get('/', function () {
    return redirect('home');
});



Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('clear/test', function () {
        Artisan::call('cache:clear');
        Artisan::call('route:clear');
        Artisan::call('config:clear');
        Artisan::call('view:clear');
        dd("success");
});

    Route::post('cashbills/auth/minprice', 'CashbillController@getAuthenticateAjax')->name('auth.minprice.post');

    Route::resource('stockmaster/stockcodes', 'StockcodeController');

    Route::resource('stockmaster/products', 'ProductController');

    Route::resource('stockmaster/category', 'CategoryController');

    Route::resource('stockmaster/brands', 'BrandController');

    Route::resource('stockmaster/locations', 'LocationController');

    Route::resource('stockmaster/uom', 'UOMController');

    Route::resource('stockmaster/adjustmentits', 'AdjustmentitController');

    Route::resource('stockmaster/adjustmentots', 'AdjustmentotController');

    Route::resource('stockmaster/reasons', 'ReasonController');

    Route::resource('stockmaster/areas', 'AreaController');

    Route::resource('stockmaster/currencies', 'CurrencyController');

    Route::resource('stockmaster/customertypes', 'CustomerController');

    Route::resource('stockmaster/salesman', 'SalesmanController');

    Route::resource('stockmaster/equipments', 'EquipmentController');

    Route::resource('stockmaster/equipments', 'EquipmentController');

    Route::resource('cylindermaster/gasracks', 'GasrackController');
    Route::get('reportprinting/gasracksactivity/print', 'GasrackActivityController@print')->name('gasracksactivity.print');
    Route::get('cylindermaster/gasracks/gasrackcylinder/{id}', 'GasrackController@storeCylinder')->name('gasracks.storeCylinder');
    Route::get('cylindermaster/gasracks/search/filter', 'Gasrackcontroller@filter_records')->name('gasracks.search.filter');
    Route::get('cylindermaster/gasracks/search/rnfilter/{accountcode}', 'Gasrackcontroller@rn_filter_records')->name('gasracks.search.rnfilter');
    Route::delete('cylindermaster/gasracks/destroycylinders/{cylinder}', 'Gasrackcontroller@destroycylinder')->name('gasracks.destroycylinder');
    Route::delete('cylindermaster/gasracks/destroyslings/{sling}', 'Gasrackcontroller@destroysling')->name('gasracks.destroysling');

    Route::resource('cylindermaster/slings', 'SlingController');

    Route::resource('cylindermaster/shackles', 'ShackleController');


    Route::get('cylindermaster/cylinders/cylinderactivity', 'CylinderController@cylinderactivity')->name('cylinders.cylinderactivity');

    Route::get('cylindermaster/cylinders/cylinderactivity/listing', 'CylinderController@cylinderActivityListing')->name('cylinders.cylinderactivity.listing');

    Route::resource('cylindermaster/cylinders', 'CylinderController');
    Route::get('reportprinting/cylindermaster/print', 'CylinderController@print')->name('cylinders.print');
    Route::get('reportprinting/cylindermovement/print', 'CylinderMovementController@print')->name('cylindersmovement.print');
    Route::get('reportprinting/cylinderledger/print', 'CylinderLedgerController@print')->name('cylinderledger.print');
    Route::get('reportprinting/cylinderRental/print', 'CylinderRentalController@print')->name('cylinderRental.print');
    Route::get('reportprinting/Location/print', 'CylinderLocationController@print')->name('cylinderlocation.print');
    Route::get('reportprinting/CylinderSummaryHolding/print', 'CylinderSummaryHoldingController@print')->name('CylinderSummaryHolding.print');
    Route::get('reportprinting/CylinderActivity/print', 'CylinderActivityController@print')->name('CylinderActivity.print');
    Route::get('reportprinting/CylinderInvalid/print', 'CylinderInvalidController@print')->name('CylinderInvalid.print');
    Route::get('cylindermaster/search/filter', 'CylinderController@filter_records')->name('cylinders.search.filter');
    Route::get('cylindermaster/search/rnfilter/{accountcode}', 'CylinderController@rn_filter_records')->name('cylinders.search.rnfilter');
    Route::get('cylindermaster/search/cylinderfilter', 'CylinderController@getCylinderDetail')->name('cylinders.search.cylinderfilter');

    Route::get('cylindermaster/search/checkfilter', 'CylinderController@check_cylinders')->name('cylinders.check.filter');

    Route::get('cylindermaster/gasracks/search/checkfilter', 'Gasrackcontroller@check_slings')->name('slings.check.filter');

    Route::get('cylindermaster/slings/search/filter', 'SlingController@filter_records')->name('slings.search.filter');

    Route::resource('cylindermaster/cylindercategory', 'CylindercategoryController');


    Route::resource('cylindermaster/cylindergroups', 'CylindergroupController');


    Route::resource('cylindermaster/cylinderproducts', 'CylinderproductController');


    Route::delete('dailypro/goods/edit/{id}', 'GoodController@destroyGooddt')->name('goods.destroyGooddt');

    Route::get('reportprinting/debtormasterlisting/print', 'DebtorController@print')->name('debtors.print');

    Route::get('reportprinting/creditormasterlisting/print', 'CreditorController@print')->name('creditors.print');

    Route::get('reportprinting/stockmasterlisting/print', 'StockcodeController@print')->name('stock.print');

    Route::get('reportprinting/stockbalance/print', 'StockreportController@printStkBal')->name('stockbal.print');

    Route::get('reportprinting/stockledger/print', 'StockLedgerController@printStkLedger')->name('stockled.print');

    Route::get('reportprinting/stockmovement/print', 'StockMovementController@printStkMovement')->name('stockmov.print');

    Route::get('reportprinting/stockvaluefifo/print', 'StockValueController@printFIFO')->name('stockvalfifo.print');

    Route::get('reportprinting/stockvalueasat/print', 'StockValueController@printASAT')->name('stockvalasat.print');

    Route::resource('stockmaster/debtors', 'DebtorController');

    Route::resource('stockmaster/creditors', 'CreditorController');

    Route::get('stockmaster/creditors/api/get', 'CreditorController@api_get')->name('creditors.api.get');

    Route::get('stockmaster/debtors/api/get', 'DebtorController@api_get')->name('debtors.api.get');

    Route::resource('cylindermaster/cylindertypes', 'CylindertypeController');

    Route::resource('cylindermaster/cylindercontainertypes', 'CylindercontainertypeController');

    Route::resource('cylindermaster/cylinderhandwheeltypes', 'CylinderhandwheeltypeController');

    Route::resource('cylindermaster/cylindervalvetypes', 'CylindervalvetypeController');

    Route::resource('cylindermaster/gasracktypes', 'GasracktypeController');

    Route::resource('cylindermaster/slingtypes', 'SlingtypeController');

    Route::resource('cylindermaster/shackletypes', 'ShackletypeController');

    Route::resource('cylindermaster/manufacturers', 'ManufacturerController');

    Route::resource('cylindermaster/ownerships', 'OwnershipController');

    Route::resource('dailypro/preturns', 'PreturnController');
    Route::get('dailypro/preturns/report/print', 'PreturnController@print')->name('preturns.print');
    Route::get('dailypro/preturns/report/jasper/{id}/purchasedreturn', 'PreturnController@jasper')->name('preturns.jasper');

    Route::delete('dailypro/preturns/edit/{id}', 'PreturnController@destroyPreturndt')->name('preturns.destroyPreturndt');

    Route::resource('dailypro/cashbills', 'CashbillController');

    Route::get('dailypro/cashbills/report/print', 'CashbillController@print')->name('cashbills.print');

    Route::get('dailypro/cashbills/report/jasper/data/cashbills', 'CashbillController@jasper')->name('cashbills.jasper');

    Route::delete('dailypro/cashbills/edit/{id}', 'CashbillController@destroyCashbilldt')->name('cashbills.destroyCashbilldt');

    // Route::resource('dailypro/invoices', 'InvoiceController');
    Route::resource('settings/documentsetups', 'DocumentSetupController');

    Route::resource('settings/dnrnsetups', 'DNRNSetupController');

    Route::resource('dailypro/quotations', 'QuotationController');
    Route::get('dailypro/quotations/report/print', 'QuotationController@print')->name('quotations.print');
    Route::get('dailypro/quotations/report/jasper/{id}/quotation', 'QuotationController@jasper')->name('quotations.jasper');

    Route::delete('dailypro/quotations/edit/{id}', 'QuotationController@destroyQuotationdt')->name('quotations.destroyQuotationdt');

    Route::resource('dailypro/deliveryorders', 'DeliveryorderController');
    Route::get('dailypro/deliveryorders/report/print', 'DeliveryorderController@print')->name('deliveryorders.print');
    Route::get('dailypro/deliveryorders/report/jasper/{id}/deliveryorder', 'DeliveryorderController@jasper')->name('deliveryorders.jasper');

app/Http/Controllers/SalesmanController.php
<?php

namespace App\Http\Controllers;

use App\Model\Salesman;
use Illuminate\Http\Request;
use PHPJasper\PHPJasper;
use Auth;

class SalesmanController extends Controller
{
    public function Index()
    {
        $data["salesman"] = Salesman::get();
        $data["page_title"] = "Salesman Item Listing";
        $data["bclvl1"] = "Salesman Item Listing";
        $data["bclvl1_url"] = route('salesman.index');

        return view('stockmaster.salesman.index', $data);
    }

    public function create()
    {
        $data["page_title"] = "Add Salesman";
        $data["bclvl1"] = "Salesman Item Listing";
        $data["bclvl1_url"] = route('salesman.index');
        $data["bclvl2"] = "Add Salesman";
        $data["bclvl2_url"] = route('salesman.create');
        return view('stockmaster.salesman.create', $data);
    }

    public function store(Request $request)
    {
        $salesman = Salesman::create([
            'code' => $request['code'],
            'descr' => $request['descr'],
            'password' => bcrypt($request['passwordcoy']),
            'password_h' => md5($request['passwordcoy']),
            'active' => $request['active'],
            'created_by'=> Auth::user()->id,
            'vehicle_no' => $request['vehicle_no']
        ]);
        return redirect()->route('salesman.index')->with('Success', 'Salesman created successfully.');
    }

    public function edit($id)
    {
        $data["salesman"] = Salesman::find($id);
        $data["page_title"] = "Edit Salesman";
        $data["bclvl1"] = "Salesman Item Listing";
        $data["bclvl1_url"] = route('salesman.index');
        $data["bclvl2"] = "Edit Salesman";
        $data["bclvl2_url"] = route('salesman.edit', ['id'=>$id]);

        return view('stockmaster.salesman.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $salesman = Salesman::find($id);
        if (isset($salesman)) {
            $salesman->update([
                'code' => $request['code'],
                'descr' => $request['descr'],
                'password' => bcrypt($request['passwordcoy']),
                'password_h' => md5($request['passwordcoy']),
                'active' => $request['active'],
                'updated_by'=> Auth::user()->id,
                'vehicle_no' => $request['vehicle_no']
            ]);
        }
        return redirect()->route('salesman.index')->with('Success', 'Salesman updated successfully.');
    }

    public function destroy(salesman $salesman)
    {
        $salesman->update([
            'deleted_by' => Auth::user()->id
        ]);
        $salesman->delete();
        return redirect()->route('salesman.index')->with('Success', 'Salesman deleted successfully.');
    }

    public function print()
    {
        $Salesmans = Salesman::all();

        if ($Salesmans->isEmpty()) {
            return "<script>alert('No Record Found');window.close();</script>";
        }

        $dataArray = array();
        $no = 1;
        foreach ($Salesmans as $Salesman) {
            $objectJSON = [];
            $objectJSON["no"] = $no;
            $objectJSON["code"] = $Salesman->code;
            $objectJSON["description"] = $Salesman->descr;
            $objectJSON["status"] = $Salesman->active ? "Active" : "Inactive";

            $no = $no + 1;
            $dataArray[] = collect($objectJSON);
        }

        $SalesmansJSON = '{"data" :' . json_encode($dataArray) . '}';

        $JsonFileName = "ReportPrintSalesman" . date("Ymdhisa");

        file_put_contents(base_path('resources/reporting/StockModule/' . $JsonFileName . '.json'), $SalesmansJSON);
        $JasperFileName = "ReportPrintSalesman" . date("Ymdhisa");;
        $file = $this->printReport($JsonFileName, $JasperFileName);

        header('Content-Description: application/pdf');
        header('Content-Type: application/pdf');
        header('Content-Disposition:; filename=' . $JasperFileName . 'pdf');
        readfile($file);
        unlink($file);
        flush();
    }

    public function printReport($JsonFileName, $JasperFileName)
    {
        $input = base_path() . '/resources/reporting/StockModule/ReportPrint.jrxml';
        $output = base_path() . '/resources/reporting/StockModule/' . $JasperFileName;

        $data_file = base_path() . '/resources/reporting/StockModule/' . $JsonFileName . '.json';

        $options = [
            'format' => ['pdf'],
            'params' => [
                "company_name" => config('config.company.name'),
                "company_no" => config('config.company.company_no'),
                "title" => "Salesman Listing Report (" .  date('d/m/Y') . ")"
            ],
            'locale' => 'en',
            'db_connection' => [
                'driver' => 'json',
                'data_file' => $data_file,
                'json_query' => 'data'
            ]
        ];

        $jasper = new PHPJasper;

        $jasper->process(
            $input,
            $output,
            $options
        )->execute();
        unlink($data_file);
        $file = base_path() . '/resources/reporting/StockModule/' . $JasperFileName . '.pdf';
        return $file;
    }

    public function download()
    {
        return "hi";
    }
}

resources/views/stockmaster/salesman/create.blade.php
@extends('master')
@section('content')


<div class="box box-solid">
    <div class="box-header"></div>
    <div class="box-body with-border">
        <form action ="{{ route('salesman.store') }}" method="POST">
            @csrf
            @include('stockmaster/salesman/form')

        </form>
    </div>
</div>

@endsection

resources/views/stockmaster/salesman/edit.blade.php
@extends('master')
@section('content')

<div class="box box-solid">
    <div class="box-header"></div>
    <div class="box-body with-border">
        <form action ="{{ route('salesman.update', $salesman->id )}}" method="POST">
        <input type="hidden" name="_method" value="PUT"/>
            @csrf
            @include('stockmaster/salesman/form')

        </form>
    </div>
</div>

@endsection

resources/views/stockmaster/salesman/form.blade.php
<div class="form-group row">
        <label for="code" class="col-md-2"> Code <span class="text-danger">*</span></label>
        <div class="col-md-10">
            <input name="code" type="text" maxlength="50" class="form-control" value="{{ isset($salesman)?$salesman->code:'' }}" required>
        </div>
    </div>
    
    <div class="form-group row">
        <label for="description" class="col-md-2">Description <span class="text-danger">*</span></label>
        <div class="col-md-10">
            <input name="descr" type="text" maxlength="100" class="form-control" value="{{ isset($salesman)?$salesman->descr:'' }}" required>
        </div>
    </div>
    
    
    <div class="form-group row">
        <label for="password" class="col-md-2">Password <span class="text-danger">*</span></label>
        <div class="col-md-10">
            <input name="passwordcoy" type="password" maxlength="100" class="form-control" value="" placeholder="********" required>
            <input name="password" type="hidden" maxlength="100" class="form-control" value="{{ isset($salesman->password)?$salesman->password:'' }}">
        </div>
    </div>

    <div class="form-group row">
        <label for="vehicle_no" class="col-md-2"> Vehicle No </label>
        <div class="col-md-10">
            <input name="vehicle_no" type="text" maxlength="50" class="form-control" value="{{ isset($salesman)?$salesman->vehicle_no:'' }}">
        </div>
    </div>

    <div class="form-group row">		
        <label class="control-label col-md-2">Active</label>
        <div class="col-md-10">
            <div class="radio-list">
                <label class="radio-inline">
                <input type="radio" name="active" value="1" {{ isset($salesman)?($salesman->active=='1')? 'checked' : '': 'checked' }}/> Active </font></label>
                <label class="radio-inline">
                <input type="radio" name="active" value="0" {{ isset($salesman)?($salesman->active=='0')? 'checked' : '': '' }}/> Non-Active </font></label>
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

resources/views/stockmaster/salesman/index.blade.php
@extends('master')

@section('content')

@if(Auth::user()->hasPermissionTo('IV_MD_SALESMAN_CR'))
<div class="row">
    <div class="col-4">
        <div class="col-lg-12 text-left" style="margin-top:10px;margin-bottom: 10px;">
            <a class="btn btn-success " href="{{ route('salesman.create') }}"> Add Salesman</a>
        </div>
    </div>
    {{-- <div class="col-4">
    </div>
    <div class="col-2" style="left: 50px;">
        <div class="col-lg-12 text-left" style="margin-top:10px;margin-bottom: 10px;">
            <a class="btn btn-primary" style="width: 100%;" target="_blank" href="{{ route('salesman.print') }}"> Print (pdf)</a>
        </div>
    </div>
    <div class="col-2">
        <div class="col-lg-12 text-left" style="margin-top:10px;margin-bottom: 10px;">
            <a class="btn btn-primary" style="width: 100%;" target="_blank" href="{{ route('salesman.download') }}"> Download
                (csv)</a>
        </div>
    </div> --}}
</div>
@endif

@if (Session::has('Success'))
<div class="alert white-alert text-secondary" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <p>{{ Session::get('Success') }}</p>
</div>

@endif

@php ($i = 0)

<div class="card">
    <div class="card-body">
        <div class="bg-white">
            <div class="table-responsive">
                <table id="salTab" class="table table-bordered table-striped" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Code</th>
                            <th>Description</th>
                            <th width="280px">More</th>
                        </tr>
                    </thead>
                    @if(sizeof($salesman) > 0)
                    <tbody>
                        @foreach ($salesman as $sm)
                        <tr>

                            <td>{{ ++$i }}</td>
                            @if(Auth::user()->hasPermissionTo('IV_MD_SALESMAN_UP'))
                                <td><a href="{{ route('salesman.edit',$sm->id) }}">{{ $sm->code }}</a></td>
                            @else
                                <td>{{  $sm->code }}</td>
                            @endif
                            {{-- <td>{{ $sm->code}}</td> --}}
                            <td>{{ $sm->descr }}</td>
                            @if(Auth::user()->hasPermissionTo('IV_MD_SALESMAN_DL'))
                                <td>
                                    <a href="{{ route('salesman.destroy', $sm->id) }}" data-method="delete"
                                        data-confirm="Confirm delete this account?">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            @else
                            <td></td>
                            @endif
                        </tr>
                        @endforeach
                    </tbody>
                    @endif
                </table>
            </div>
        </div>
    </div>
</div>



{{-- {!! $salesman->links() !!} --}}

@endsection

@push('scripts')
<script>
$(document).ready(function() {

            $('#salTab').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'excelHtml5',
                    'csvHtml5',
                    'pdfHtml5'
                ]
            });
        } );
</script>

<script src="https://cdn.datatables.net/buttons/1.6.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.html5.min.js"></script>
@endpush